client_website/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", views.HomeView.as_view()),
    path("product/", include("product.urls")),
    path("customer/",include("customer.urls")),
    path('admin/', admin.site.urls),
]

customer/urls.py
from django.urls import path
from . import views

app_name = "customer"
urlpatterns = [
    path("<int:id>/",views.CustomerView.as_view(),name = "customer_view"),
    path("signup/",views.SignUp.as_view(),name="signup"),
    path("login/", views.LogIn.as_view(),name="login")
]   

product/urls.py
from django.urls import path
from . import views

app_name = "product"
urlpatterns = [

]

customer/models.py
from django.db import models

class Customer(models.Model):

    manager = models.CharField(max_length = 30,blank=True)
    username = models.CharField(max_length = 40,blank = False)
    company_name = models.CharField(max_length = 100,blank=True)
    phone_number = models.CharField(max_length = 15,blank=True)
    email = models.EmailField()
    account_number = models.CharField(max_length = 30,blank=True)
    ifsc_code = models.CharField(max_length = 20,blank=True)
    bank_name = models.CharField(max_length = 30,blank=True)
    creation_date = models.DateTimeField(auto_now_add = True,blank=True)
    gst_number = models.CharField(max_length = 20,blank=True)
    street = models.CharField(max_length = 50,blank=True)
    zipcode = models.CharField(max_length = 10,blank=True)
    city = models.CharField(max_length = 20,blank=True)
    state = models.CharField(max_length = 20,blank=True)
    country = models.CharField(max_length = 20,blank=True)
    seller_id = models.CharField(max_length = 20,blank=True)
    password = models.CharField(max_length = 20,blank=True)

    def __str__(self):
        return self.username

customer/forms.py
from django import forms

class SignUpForm(forms.Form):

    email = forms.EmailField(label = "E-Mail", max_length = 40)
    password = forms.CharField(label = "Password",max_length = 20)


class LoginForm(forms.Form):
     
    username = forms.CharField(label = "Username", max_length = 40)
    password = forms.CharField(label = 'Password', max_length = 30)


class CustomerForm(forms.Form):

    manager = forms.CharField(max_length = 30)
    username = forms.CharField(max_length = 40)
    company_name = forms.CharField(max_length = 100)
    phone_number = forms.CharField(max_length = 15)
    email = forms.EmailField()
    account_number = forms.CharField(max_length = 30)
    ifsc_code = forms.CharField(max_length = 20)
    bank_name = forms.CharField(max_length = 30)
    creation_date = forms.DateTimeField()
    gst_number = forms.CharField(max_length = 20)
    street = forms.CharField(max_length = 50)
    zipcode = forms.CharField(max_length = 10)
    city = forms.CharField(max_length = 20)
    state = forms.CharField(max_length = 20)
    country = forms.CharField(max_length = 20)
    seller_id = forms.CharField(max_length = 20)
    password = forms.CharField(max_length = 20)

customer/views.py
import logging
_logger = logging.getLogger(__name__)
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView ,View
from .forms import SignUpForm, LoginForm, CustomerForm
from .models import Customer


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'customers/signup.html'

    def get(self,request):
        form = SignUpForm()
        return render(request,"customers/signup.html",{"form":form})

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        # _logger.error("request------------->%r",request.POST)
        if form.is_valid():
            email = request.POST.get("email")
            pwd = request.POST.get("password")
            customer = Customer(email=email,password = pwd)
            customer.save()
            return HttpResponseRedirect(reverse('customer:login'))
        return render(request, "customers/signup.html",{"form":form})


class LogIn(View):

    def get(self,request, *args, **kwargs):
        form = LoginForm()
        return render(request,"customers/login.html",{"form":form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password")
            try:
                customer = get_object_or_404(Customer,username = username, password = password)
                _logger.error("customer ======> %r",customer)
            except Exception as e:  
                _logger.error("error =====> %r",str(e))
            else:
                customer_id = customer.id
                return HttpResponseRedirect(
                    reverse('customer:customer_view',kwargs={'id': customer_id}))
        return render(request, "customer/login.html",{"form":form})


class CustomerView(View):

    def get(self, request):
        return render(request, "customer/customer_dashboard.html")

templates/customers/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/customers/login.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <h1>LOG IN</h1>
  <form action="{% url 'customer:login' %}" method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <!-- <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div> -->
    <!-- <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div> -->
    <!-- <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div> -->
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <body>

templates/customers/scripts.html
{% load static %}


<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

templates/customers/signup.html
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <h1>SIGN UP</h1>
<form action="{% url 'customer:signup' %}" method = "post">
  {% csrf_token %}
  {{form.as_p}}
  <!-- <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
  </div> -->
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<body>